apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
spec:
  selector:
    istio: gateway-in-cluster
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - argocd.thecloudsninja.com
      tls:
        mode: SIMPLE
        credentialName: argocd-tls
