apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.cloudsninja.com"
  dnsNames:
    - "*.cloudsninja.com"
