apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "{{ .Values.commonName }}"
  dnsNames:
    - "{{ .Values.commonName }}"