gateway:
  selector: istio-ingressgateway
  host: my-gateway.example.com
  tlsSecretName: my-gateway-tls

  podAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  serviceAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  serviceAccountAnnotations:
    argocd.argoproj.io/sync-wave: "1"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
